### ISSUE TITLE
Budget display needs to consider overexpenditures/underexpenditures

### ISSUE THREAD

**Issue by ctgraham** [ulsdevteam/oafeefund#1]
Actual expenses can vary from requested amounts due to fees and discounts.  The budget summary needs to reflect actual + approved expenses, not just approved expenses.

https://github.com/ulsdevteam/oafeefund/blob/85223ac0988352d66b5b522efacaa56c1b6706cd/src/Controller/BudgetsController.php#L23-L45

**Comment by edensung25** [comment]
The change is committed on branch "fix" and I applied it on stage site.

**Comment by ctgraham** [comment]
Comment added:
https://github.com/ulsdevteam/oafeefund/commit/81ee7da0d01c3d193e7f06d9ccff33e2fc7feef4#r33350516

If you reference an issue by number in a commit message, e.g. "#1: fixed something" or "ulsdevteam/oafeefund#1: fixed a thing", this will automatically connect the commit with this issue.

**Comment by ctgraham** [comment]
Resolved with:
https://github.com/ulsdevteam/oafeefund/commit/69b418f11da175b7eb7fd478f82b1836d20c93ee
and:
https://github.com/ulsdevteam/oafeefund/commit/509d0df8a49ff701ff6c93d6a8f3892a85e413f4
